package com.nbchina.ws.api.entinfo.riskinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-11-23T10:23:57.378+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", name = "RiskInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface RiskInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectEquityPledgeList", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectEquityPledgeList")
    @WebMethod
    @ResponseWrapper(localName = "selectEquityPledgeListResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectEquityPledgeListResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectEquityPledgeList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectLegalNoticeDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLegalNoticeDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectLegalNoticeDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLegalNoticeDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.LegalNotice selectLegalNoticeDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectDishonestInfoListBrief", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectDishonestInfoListBrief")
    @WebMethod
    @ResponseWrapper(localName = "selectDishonestInfoListBriefResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectDishonestInfoListBriefResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectDishonestInfoListBrief(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectExecutedPersonList", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectExecutedPersonList")
    @WebMethod
    @ResponseWrapper(localName = "selectExecutedPersonListResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectExecutedPersonListResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectExecutedPersonList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectLicenseByAreacode", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLicenseByAreacode")
    @WebMethod
    @ResponseWrapper(localName = "selectLicenseByAreacodeResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLicenseByAreacodeResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectLicenseByAreacode(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectJudicialSaleDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudicialSaleDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectJudicialSaleDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudicialSaleDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.JudicialSale selectJudicialSaleDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectChattelMortgageList", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectChattelMortgageList")
    @WebMethod
    @ResponseWrapper(localName = "selectChattelMortgageListResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectChattelMortgageListResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectChattelMortgageList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectLicenseByCounter", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLicenseByCounter")
    @WebMethod
    @ResponseWrapper(localName = "selectLicenseByCounterResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLicenseByCounterResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectLicenseByCounter(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countRiskInfoByKeyword", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.CountRiskInfoByKeyword")
    @WebMethod
    @ResponseWrapper(localName = "countRiskInfoByKeywordResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.CountRiskInfoByKeywordResponse")
    public java.util.List<java.lang.Long> countRiskInfoByKeyword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectJudgementListBrief", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudgementListBrief")
    @WebMethod
    @ResponseWrapper(localName = "selectJudgementListBriefResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudgementListBriefResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectJudgementListBrief(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPenaltyByCounter", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyByCounter")
    @WebMethod
    @ResponseWrapper(localName = "selectPenaltyByCounterResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyByCounterResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectPenaltyByCounter(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectChattelMortgageDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectChattelMortgageDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectChattelMortgageDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectChattelMortgageDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.ChattelMortgage selectChattelMortgageDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectLegalNoticeListBrief", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLegalNoticeListBrief")
    @WebMethod
    @ResponseWrapper(localName = "selectLegalNoticeListBriefResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLegalNoticeListBriefResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectLegalNoticeListBrief(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectDishonestInfoDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectDishonestInfoDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectDishonestInfoDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectDishonestInfoDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.DishonestInfo selectDishonestInfoDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectLicenseDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLicenseDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectLicenseDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectLicenseDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.License selectLicenseDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countRiskInfoByEntUuid", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.CountRiskInfoByEntUuid")
    @WebMethod
    @ResponseWrapper(localName = "countRiskInfoByEntUuidResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.CountRiskInfoByEntUuidResponse")
    public java.util.List<java.lang.Integer> countRiskInfoByEntUuid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectBusinessExceptionList", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectBusinessExceptionList")
    @WebMethod
    @ResponseWrapper(localName = "selectBusinessExceptionListResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectBusinessExceptionListResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectBusinessExceptionList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPenaltyNumberByAreacode", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyNumberByAreacode")
    @WebMethod
    @ResponseWrapper(localName = "selectPenaltyNumberByAreacodeResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyNumberByAreacodeResponse")
    public java.util.List<com.nbchina.ws.api.entinfo.riskinfo.CommonGridListEntityVo> selectPenaltyNumberByAreacode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPenaltyByAreacode", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyByAreacode")
    @WebMethod
    @ResponseWrapper(localName = "selectPenaltyByAreacodeResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyByAreacodeResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectPenaltyByAreacode(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectBusinessChangeList", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectBusinessChangeList")
    @WebMethod
    @ResponseWrapper(localName = "selectBusinessChangeListResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectBusinessChangeListResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectBusinessChangeList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectJudicialSaleListBrief", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudicialSaleListBrief")
    @WebMethod
    @ResponseWrapper(localName = "selectJudicialSaleListBriefResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudicialSaleListBriefResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectJudicialSaleListBrief(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectJudgesByKeyword", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudgesByKeyword")
    @WebMethod
    @ResponseWrapper(localName = "selectJudgesByKeywordResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudgesByKeywordResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectJudgesByKeyword(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPenaltyDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectPenaltyDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectPenaltyDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.Penalty selectPenaltyDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectJudgementDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudgementDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectJudgementDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectJudgementDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.Judgement selectJudgementDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectOpeningNoticeDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectOpeningNoticeDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectOpeningNoticeDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectOpeningNoticeDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.OpeningNotice selectOpeningNoticeDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectEquityPledgeDetail", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectEquityPledgeDetail")
    @WebMethod
    @ResponseWrapper(localName = "selectEquityPledgeDetailResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectEquityPledgeDetailResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.EquityPledge selectEquityPledgeDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectOpeningNoticeList", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectOpeningNoticeList")
    @WebMethod
    @ResponseWrapper(localName = "selectOpeningNoticeListResponse", targetNamespace = "http://riskInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.riskinfo.SelectOpeningNoticeListResponse")
    public com.nbchina.ws.api.entinfo.riskinfo.QueryResult selectOpeningNoticeList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
