package com.nbchina.ws.api.entinfo.intelproperty.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.nbchina.ws.api.entinfo.intelproperty.IntelInterface;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-11-23T10:24:11.930+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "IntelImplService", 
                  wsdlLocation = "http://localhost/DataService/webservice/intelServer?wsdl",
                  targetNamespace = "http://impl.intelProperty.entInfo.api.ws.nbchina.com/") 
public class IntelImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.intelProperty.entInfo.api.ws.nbchina.com/", "IntelImplService");
    public final static QName IntelImplPort = new QName("http://impl.intelProperty.entInfo.api.ws.nbchina.com/", "IntelImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/DataService/webservice/intelServer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IntelImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/DataService/webservice/intelServer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IntelImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IntelImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntelImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntelImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntelImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntelImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IntelInterface
     */
    @WebEndpoint(name = "IntelImplPort")
    public IntelInterface getIntelImplPort() {
        return super.getPort(IntelImplPort, IntelInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntelInterface
     */
    @WebEndpoint(name = "IntelImplPort")
    public IntelInterface getIntelImplPort(WebServiceFeature... features) {
        return super.getPort(IntelImplPort, IntelInterface.class, features);
    }

}
