package com.nbchina.ws.api.entinfo.operinfo.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.nbchina.ws.api.entinfo.operinfo.OperInterface;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-11-23T10:24:04.130+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "OperImplService", 
                  wsdlLocation = "http://localhost/DataService/webservice/operServer?wsdl",
                  targetNamespace = "http://impl.operInfo.entInfo.api.ws.nbchina.com/") 
public class OperImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.operInfo.entInfo.api.ws.nbchina.com/", "OperImplService");
    public final static QName OperImplPort = new QName("http://impl.operInfo.entInfo.api.ws.nbchina.com/", "OperImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/DataService/webservice/operServer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OperImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/DataService/webservice/operServer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OperImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OperImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OperImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OperImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OperInterface
     */
    @WebEndpoint(name = "OperImplPort")
    public OperInterface getOperImplPort() {
        return super.getPort(OperImplPort, OperInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperInterface
     */
    @WebEndpoint(name = "OperImplPort")
    public OperInterface getOperImplPort(WebServiceFeature... features) {
        return super.getPort(OperImplPort, OperInterface.class, features);
    }

}
