package com.nbchina.ws.api.entinfo.baseinfo.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.nbchina.ws.api.entinfo.baseinfo.BaseInterface;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-11-23T10:23:51.620+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "BaseImplService", 
                  wsdlLocation = "http://localhost/DataService/webservice/baseServer?wsdl",
                  targetNamespace = "http://impl.baseInfo.entInfo.api.ws.nbchina.com/") 
public class BaseImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.baseInfo.entInfo.api.ws.nbchina.com/", "BaseImplService");
    public final static QName BaseImplPort = new QName("http://impl.baseInfo.entInfo.api.ws.nbchina.com/", "BaseImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/DataService/webservice/baseServer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaseImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/DataService/webservice/baseServer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BaseImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaseImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BaseImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BaseImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BaseImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BaseInterface
     */
    @WebEndpoint(name = "BaseImplPort")
    public BaseInterface getBaseImplPort() {
        return super.getPort(BaseImplPort, BaseInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseInterface
     */
    @WebEndpoint(name = "BaseImplPort")
    public BaseInterface getBaseImplPort(WebServiceFeature... features) {
        return super.getPort(BaseImplPort, BaseInterface.class, features);
    }

}
