package com.nbchina.ws.api.entinfo.operinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-11-23T10:24:04.083+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", name = "OperInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface OperInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectJobList", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectJobList")
    @WebMethod
    @ResponseWrapper(localName = "selectJobListResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectJobListResponse")
    public com.nbchina.ws.api.entinfo.operinfo.QueryResult selectJobList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectNewsByKeyword", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectNewsByKeyword")
    @WebMethod
    @ResponseWrapper(localName = "selectNewsByKeywordResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectNewsByKeywordResponse")
    public com.nbchina.ws.api.entinfo.operinfo.QueryResult selectNewsByKeyword(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectBiddingList", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectBiddingList")
    @WebMethod
    @ResponseWrapper(localName = "selectBiddingListResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectBiddingListResponse")
    public com.nbchina.ws.api.entinfo.operinfo.QueryResult selectBiddingList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countNewsByKeyword", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountNewsByKeyword")
    @WebMethod
    @ResponseWrapper(localName = "countNewsByKeywordResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountNewsByKeywordResponse")
    public java.lang.Long countNewsByKeyword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countOperInfoByKeyword", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountOperInfoByKeyword")
    @WebMethod
    @ResponseWrapper(localName = "countOperInfoByKeywordResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountOperInfoByKeywordResponse")
    public java.util.List<java.lang.Long> countOperInfoByKeyword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectByNewsPK", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectByNewsPK")
    @WebMethod
    @ResponseWrapper(localName = "selectByNewsPKResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectByNewsPKResponse")
    public com.nbchina.ws.api.entinfo.operinfo.News selectByNewsPK(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countJudgementByKeyword", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountJudgementByKeyword")
    @WebMethod
    @ResponseWrapper(localName = "countJudgementByKeywordResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountJudgementByKeywordResponse")
    public java.lang.Long countJudgementByKeyword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectFinancingList", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectFinancingList")
    @WebMethod
    @ResponseWrapper(localName = "selectFinancingListResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectFinancingListResponse")
    public com.nbchina.ws.api.entinfo.operinfo.QueryResult selectFinancingList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countOperInfoByEntUuid", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountOperInfoByEntUuid")
    @WebMethod
    @ResponseWrapper(localName = "countOperInfoByEntUuidResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.CountOperInfoByEntUuidResponse")
    public java.util.List<java.lang.Integer> countOperInfoByEntUuid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectNewsList", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectNewsList")
    @WebMethod
    @ResponseWrapper(localName = "selectNewsListResponse", targetNamespace = "http://operInfo.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.operinfo.SelectNewsListResponse")
    public com.nbchina.ws.api.entinfo.operinfo.QueryResult selectNewsList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
