package com.nbchina.ws.api.entinfo.intelproperty;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-11-23T10:24:11.883+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", name = "IntelInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface IntelInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectDomainList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectDomainList")
    @WebMethod
    @ResponseWrapper(localName = "selectDomainListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectDomainListResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectDomainList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPatentList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentList")
    @WebMethod
    @ResponseWrapper(localName = "selectPatentListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentListResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectPatentList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countIntelProByEntUuid", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.CountIntelProByEntUuid")
    @WebMethod
    @ResponseWrapper(localName = "countIntelProByEntUuidResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.CountIntelProByEntUuidResponse")
    public java.util.List<java.lang.Integer> countIntelProByEntUuid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectTrademarkByPK", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectTrademarkByPK")
    @WebMethod
    @ResponseWrapper(localName = "selectTrademarkByPKResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectTrademarkByPKResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.TrademarkWithBLOBs selectTrademarkByPK(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectCertificationList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCertificationList")
    @WebMethod
    @ResponseWrapper(localName = "selectCertificationListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCertificationListResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectCertificationList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPatentByPK", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentByPK")
    @WebMethod
    @ResponseWrapper(localName = "selectPatentByPKResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentByPKResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.Patent selectPatentByPK(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPatentTypeList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentTypeList")
    @WebMethod
    @ResponseWrapper(localName = "selectPatentTypeListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentTypeListResponse")
    public java.util.List<java.lang.String> selectPatentTypeList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectCopyrightList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCopyrightList")
    @WebMethod
    @ResponseWrapper(localName = "selectCopyrightListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCopyrightListResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectCopyrightList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectSoftwareCopyrightList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectSoftwareCopyrightList")
    @WebMethod
    @ResponseWrapper(localName = "selectSoftwareCopyrightListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectSoftwareCopyrightListResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectSoftwareCopyrightList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectCertificationByConditions", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCertificationByConditions")
    @WebMethod
    @ResponseWrapper(localName = "selectCertificationByConditionsResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCertificationByConditionsResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectCertificationByConditions(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPatentByConditions", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentByConditions")
    @WebMethod
    @ResponseWrapper(localName = "selectPatentByConditionsResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectPatentByConditionsResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectPatentByConditions(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectTrademarkList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectTrademarkList")
    @WebMethod
    @ResponseWrapper(localName = "selectTrademarkListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectTrademarkListResponse")
    public com.nbchina.ws.api.entinfo.intelproperty.QueryResult selectTrademarkList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectCertificationTypeList", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCertificationTypeList")
    @WebMethod
    @ResponseWrapper(localName = "selectCertificationTypeListResponse", targetNamespace = "http://intelProperty.entInfo.api.ws.nbchina.com/", className = "com.nbchina.ws.api.entinfo.intelproperty.SelectCertificationTypeListResponse")
    public java.util.List<java.lang.String> selectCertificationTypeList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
