package com.nbchina.ws.api.entinfo.riskinfo.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.nbchina.ws.api.entinfo.riskinfo.RiskInterface;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-11-23T10:23:57.425+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "RiskImplService", 
                  wsdlLocation = "http://localhost/DataService/webservice/riskServer?wsdl",
                  targetNamespace = "http://impl.riskInfo.entInfo.api.ws.nbchina.com/") 
public class RiskImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.riskInfo.entInfo.api.ws.nbchina.com/", "RiskImplService");
    public final static QName RiskImplPort = new QName("http://impl.riskInfo.entInfo.api.ws.nbchina.com/", "RiskImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/DataService/webservice/riskServer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RiskImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/DataService/webservice/riskServer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RiskImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RiskImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RiskImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RiskImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RiskImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RiskImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RiskInterface
     */
    @WebEndpoint(name = "RiskImplPort")
    public RiskInterface getRiskImplPort() {
        return super.getPort(RiskImplPort, RiskInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RiskInterface
     */
    @WebEndpoint(name = "RiskImplPort")
    public RiskInterface getRiskImplPort(WebServiceFeature... features) {
        return super.getPort(RiskImplPort, RiskInterface.class, features);
    }

}
